version: '2.2'
services:
  app:
    container_name: mock-api_rails
    build:
      network: host
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: docker/rails/provision.sh
    ports:
      - '3000:3000'
    volumes:
      - /var/tmp
      - ./log:/app/log
    extends:
      file: ./docker/mysql/password.yml
      service: password
    env_file: .env
    depends_on:
      - db
  db:
    container_name: mock-api_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password
  nginx:
    container_name: mock-api_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /usr/local/ssl/certs:/etc/nginx/certs
    volumes_from:
      - app
  # caddy:
  #   container_name: mock-api_caddy
  #   image: caddy:2.6.2-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "443:443/udp"
  #   volumes:
  #     - $PWD/Caddyfile:/etc/caddy/Caddyfile

volumes:
  db_data:
