---
openapi: 3.0.3
info:
  title: API Placeholder V2
  version: v2
paths:
  "/api/v2/blogs":
    post:
      summary: Creates a blog
      tags:
      - Blogs
      parameters: []
      responses:
        '201':
          description: Blog created
        '422':
          description: Unprocessable entity
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                blog[title]:
                  type: string
                  example: My Blog
                  description: Title of the blog
                blog[content]:
                  type: string
                  example: My Blog Content
                  description: Content of the blog
                blog[image]:
                  type: string
                  format: binary
                  description: Image of the blog
              required:
              - blog[title]
              - blog[content]
    get:
      summary: Retrieves blogs as a list
      tags:
      - Blogs
      parameters:
      - name: page
        in: query
        description: Page number. Default is `1`
        required: false
        schema:
          type: number
      - name: items
        in: query
        description: Number of items per page. Default is `20`
        required: false
        schema:
          type: number
      - name: search
        in: query
        description: Search title or content containing the query
        required: false
        schema:
          type: string
      - name: sort_by
        in: query
        description: Valid value is one of `[id, title, content, created_at, updated_at]`.
          Default is `created_at`
        required: false
        schema:
          type: string
      - name: sort_direction
        in: query
        description: Valid value is `asc` or `desc`. Default is `desc`
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            email:
                              type: string
                            name:
                              type: string
                            avatar:
                              type: object
                              properties:
                                url:
                                  type: string
                              required:
                              - url
                            created_at:
                              type: string
                            updated_at:
                              type: string
                          required:
                          - email
                          - name
                          - avatar
                          - created_at
                          - updated_at
                      pagination:
                        type: object
                        properties:
                          count:
                            type: number
                            description: Total number of items
                          page:
                            type: number
                            description: Current page
                          offset:
                            type: number
                            description: Items per page
                          total:
                            type: number
                            description: Total number of pages
                          prev:
                            type: number
                            description: Previous page
                          next:
                            type: number
                            description: Next page
                        required:
                        - count
                        - page
                        - offset
                        - total
                        - prev
                        - next
                    required:
                    - items
                    - pagination
                required:
                - data
  "/api/v2/blogs/{id}":
    get:
      summary: Retrieves a blog by id
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    example: My Blog
                    description: Title of the blog
                  content:
                    type: string
                    example: My Blog Content
                    description: Content of the blog
                  image:
                    type: object
                    properties:
                      url:
                        type: string
                        example: http://localhost:3000/images/fallback/default.png
                        description: Image of the blog
                  created_at:
                    type: string
                    example: '2019-01-01T00:00:00.000Z'
                    description: Created at of the blog
                  updated_at:
                    type: string
                    example: '2019-01-01T00:00:00.000Z'
                    description: Updated at of the blog
        '404':
          description: Blog not found
        '406':
          description: Unsupported accept header
    put:
      summary: Update a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Blog updated
        '404':
          description: Blog not found
        '422':
          description: Unprocessable request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                blog[title]:
                  type: string
                  example: My Blog
                  description: Title of the blog
                blog[content]:
                  type: string
                  example: My Blog Content
                  description: Content of the blog
                blog[image]:
                  type: string
                  format: binary
                  description: Image of the blog
              required:
              - blog[title]
              - blog[content]
    delete:
      summary: Delete a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Blog deleted
  "/api/v2/login":
    post:
      summary: Login
      tags:
      - Auhorization
      parameters: []
      responses:
        '200':
          description: Logged in successfully with the refresh token
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@simple.me
                  description: Email of the user
                password:
                  type: string
                  example: password
                  description: Password of the user
                remember_me:
                  type: boolean
                  example: true
                  description: Remember me to get the refresh token
              required:
              - email
              - password
  "/api/v2/logout":
    delete:
      summary: Logout
      tags:
      - Auhorization
      security:
      - BearerAuth: []
      responses:
        '204':
          description: Logged out successfully
        '401':
          description: Unauthorized
  "/api/v2/me":
    get:
      summary: Get my profile
      tags:
      - Auhorization
      security:
      - BearerAuth: []
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
  "/api/v2/refresh_tokens":
    post:
      summary: Refresh Access Token
      tags:
      - Auhorization
      parameters: []
      responses:
        '200':
          description: Token has been reset successfully
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: sometoken628396
                  description: The refresh token
  "/api/v2/users":
    post:
      summary: Register
      tags:
      - Auhorization
      parameters: []
      responses:
        '201':
          description: Register successfully
        '422':
          description: Register failed
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user[name]:
                  type: string
                  description: Within 50 characters
                user[email]:
                  type: string
                user[password]:
                  type: string
                  description: At least 8 characters
                user[avatar]:
                  type: string
                  format: binary
              required:
              - user[name]
              - user[email]
              - user[password]
servers:
- url: "{heroku}"
  variables:
    heroku:
      default: https://api-placeholder.herokuapp.com
- url: "{localhost}"
  variables:
    localhost:
      default: http://localhost:3000
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Blog:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
          example: My Blog
          description: Title of the blog
        content:
          type: string
          example: My Blog Content
          description: Content of the blog
        image:
          type: object
          properties:
            url:
              type: string
              example: http://localhost:3000/images/fallback/default.png
              description: Image of the blog
          required:
          - url
        created_at:
          type: string
          example: '2019-01-01T00:00:00.000Z'
          description: Created at of the blog
        updated_at:
          type: string
          example: '2019-01-01T00:00:00.000Z'
          description: Updated at of the blog
      required:
      - id
      - title
      - content
      - image
      - created_at
      - updated_at
    User:
      type: object
      properties:
        email:
          type: string
        name:
          type: string
        avatar:
          type: object
          properties:
            url:
              type: string
          required:
          - url
        created_at:
          type: string
        updated_at:
          type: string
      required:
      - email
      - name
      - avatar
      - created_at
      - updated_at
    Pagination:
      type: object
      properties:
        count:
          type: number
          description: Total number of items
        page:
          type: number
          description: Current page
        offset:
          type: number
          description: Items per page
        total:
          type: number
          description: Total number of pages
        prev:
          type: number
          description: Previous page
        next:
          type: number
          description: Next page
      required:
      - count
      - page
      - offset
      - total
      - prev
      - next
    Error:
      type: object
      properties:
        message:
          type: string
        type:
          type: string
        status:
          type: string
        path:
          type: string
        error_code:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              code:
                type: string
              message:
                type: string
            required:
            - field
            - code
            - message
      required:
      - message
      - type
      - status
      - path
      - error_code
      - errors
