---
openapi: 3.0.3
info:
  title: API Placeholder
  version: v1
paths:
  "/api/v1/blogs":
    post:
      summary: Creates a blog
      tags:
      - Blogs
      parameters: []
      responses:
        '201':
          description: Blog created
        '422':
          description: Unprocessable entity
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                blog[title]:
                  type: string
                  example: My Blog
                  description: Title of the blog
                blog[content]:
                  type: string
                  example: My Blog Content
                  description: Content of the blog
                blog[image]:
                  type: string
                  format: binary
                  description: Image of the blog
              required:
              - blog[title]
              - blog[content]
    get:
      summary: Retrieves blogs as a list
      tags:
      - Blogs
      parameters:
      - name: page
        in: query
        description: Page number. Default is `1`
        schema:
          type: number
      - name: items
        in: query
        description: Number of items per page. Default is `20`
        schema:
          type: number
      - name: search
        in: query
        description: Search title or content containing the query
        schema:
          type: string
      - name: sort_by
        in: query
        description: Valid value is one of `[id, title, content, created_at, updated_at]`.
          Default is `created_at`
        schema:
          type: string
      - name: sort_direction
        in: query
        description: Valid value is `asc` or `desc`. Default is `desc`
        schema:
          type: string
      responses:
        '200':
          description: Blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                          description: Title of the blog
                        content:
                          type: string
                          description: Content of the blog
                        image:
                          type: object
                          description: Image of the blog
                          properties:
                            url:
                              type: string
                              description: Image url
                        created_at:
                          type: string
                          description: Created at of the blog
                        updated_at:
                          type: string
                          description: Updated at of the blog
                  pagy:
                    type: object
                    properties:
                      count:
                        type: integer
                      page:
                        type: integer
                      items:
                        type: integer
                      pages:
                        type: integer
                      last:
                        type: integer
                      in:
                        type: integer
                      from:
                        type: integer
                      to:
                        type: integer
                      prev:
                        type: integer
                      next:
                        type: integer
                required:
                - data
                - pagy
  "/api/v1/blogs/{id}":
    get:
      summary: Retrieves a blog by id
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                    example: My Blog
                    description: Title of the blog
                  content:
                    type: string
                    example: My Blog Content
                    description: Content of the blog
                  image:
                    type: object
                    properties:
                      url:
                        type: string
                        example: http://localhost:3000/images/fallback/default.png
                        description: Image of the blog
                  created_at:
                    type: string
                    example: '2019-01-01T00:00:00.000Z'
                    description: Created at of the blog
                  updated_at:
                    type: string
                    example: '2019-01-01T00:00:00.000Z'
                    description: Updated at of the blog
        '404':
          description: Blog not found
    put:
      summary: Update a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Blog updated
        '404':
          description: Blog not found
        '422':
          description: Unprocessable request
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                blog[title]:
                  type: string
                  example: My Blog
                  description: Title of the blog
                blog[content]:
                  type: string
                  example: My Blog Content
                  description: Content of the blog
                blog[image]:
                  type: string
                  format: binary
                  description: Image of the blog
              required:
              - blog[title]
              - blog[content]
    delete:
      summary: Delete a blog
      tags:
      - Blogs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Blog deleted
  "/api/v1/login":
    post:
      summary: Login
      tags:
      - Auhorization
      parameters: []
      responses:
        '200':
          description: Logged in successfully with the refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
                required:
                - token
                - refresh_token
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: example@simple.me
                  description: Email of the user
                password:
                  type: string
                  example: password
                  description: Password of the user
                remember_me:
                  type: boolean
                  example: true
                  description: Remember me to get the refresh token
  "/api/v1/logout":
    delete:
      summary: Logout
      tags:
      - Auhorization
      security:
      - Authorization: []
      responses:
        '204':
          description: Logged out successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/me":
    get:
      summary: Get my profile
      tags:
      - Auhorization
      security:
      - Authorization: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      avatar:
                        type: object
                        properties:
                          url:
                            type: string
                        required:
                        - url
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - email
                    - name
                    - avatar
                    - created_at
                    - updated_at
                required:
                - user
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
  "/api/v1/refresh_tokens":
    post:
      summary: Refresh Access Token
      tags:
      - Auhorization
      parameters: []
      responses:
        '200':
          description: Token has been reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
                required:
                - token
                - refresh_token
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: some-token
                  description: The refresh token
  "/api/v1/users":
    post:
      summary: Register
      tags:
      - Auhorization
      parameters: []
      responses:
        '201':
          description: Register successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      name:
                        type: string
                      avatar:
                        type: object
                        properties:
                          url:
                            type: string
                        required:
                        - url
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - email
                    - name
                    - avatar
                    - created_at
                    - updated_at
                required:
                - user
        '422':
          description: Register failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: array
                    items:
                      type: string
                  email:
                    type: array
                    items:
                      type: string
                  password:
                    type: array
                    items:
                      type: string
                  avatar:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user[name]:
                  type: string
                  description: Within 50 characters
                user[email]:
                  type: string
                user[password]:
                  type: string
                  description: At least 8 characters
                user[avatar]:
                  type: string
                  format: binary
              required:
              - user[name]
              - user[email]
              - user[password]
servers:
- url: "{heroku}"
  variables:
    heroku:
      default: https://api-placeholder.herokuapp.com
- url: "{localhost}"
  variables:
    localhost:
      default: http://localhost:3000
